#!/bin/bash
#
# Builda e roda os servidores
#

set -e

ROOT_DIR=$(pwd)
HOST="localhost:8080/healthcheck"

has_artifact() {
    if [[ -d "$1/target" ]]; then
        echo "Artifact found"
    else
        echo "Artifact not found"
        cd "$ROOT_DIR/$1"
        mvn clean install
        cd $ROOT_DIR
    fi
}

wait_kill() {
    if [[ "$1" == "-d" || "$1" == "--die" ]]; then
        server_pid=$2
        echo "Server PID: $server_pid"
        trigger_ab
        kill -9 $server_pid
    fi
}

trigger_requests() {
    for i in $(seq 1 1000); do
        curl -s $HOST >/dev/null
    done
}

trigger_ab() {
    ab -n 100000 -c 100 -q $HOST >/dev/null
}

activej() {
    has_artifact poc-activej
    java -jar poc-activej/target/poc-activej-5.2-jar-with-dependencies.jar &

    wait_kill $1 $!
}

dropwizard() {
    has_artifact poc-dropwizard
    java -jar poc-dropwizard/target/poc-dropwizard-1.0-SNAPSHOT.jar server &

    wait_kill $1 $!
}

jooby() {
    has_artifact poc-jooby
    java -jar poc-jooby/target/poc-jooby-1.0.0.jar &

    wait_kill $1 $!
}

micronaut() {
    has_artifact poc-micronaut
    java -jar poc-micronaut/target/poc-micronaut-0.1.jar &

    wait_kill $1 $!
}

quarkus() {
    has_artifact poc-quarkus
    java -jar poc-quarkus/target/quarkus-app/quarkus-run.jar &

    wait_kill $1 $!
}

spring_mvc() {
    has_artifact poc-spring-mvc
    java -jar poc-spring-mvc/target/poc-spring-mvc-0.0.1-SNAPSHOT.jar &

    wait_kill $1 $!
}

spring_webflux() {
    has_artifact poc-spring-webflux
    java -jar poc-spring-webflux/target/poc-spring-webflux-0.0.1-SNAPSHOT.jar &

    wait_kill $1 $!
}

thorntail() {
    has_artifact poc-thorntail
    java -jar poc-thorntail/target/poc-thorntail-thorntail.jar &

    wait_kill $1 $!
}

vertx() {
    has_artifact poc-vertx
    java -jar poc-vertx/target/poc-activex-1.0.0-fat.jar &

    wait_kill $1 $!
}


if [[ -z "$1" ]]; then
    echo "no arguments provided"
    exit 1
fi

MENSAGEM_USO="
Uso: $0 [SERVER_NAME | -h] [-d]

    -h, --help      Mostra esta ajuda e sai
    -d, --die       Roda o servidor em modo benchmark. Efetua $NUM_REQUESTS 
                    requisições de healthcheck e encerra o servidor.

Server options:     activej, dropwizard, jooby, micronaut, quarkus,
                    spring-mvc, spring-webflux, thorntail, vertx

To run the server in benchmark mode use:
    ./start foo --die
"

case "$1" in
    activej) activej $2;;
    dropwizard) dropwizard $2;;
    jooby) jooby $2;;
    micronaut) micronaut $2;;
    quarkus) quarkus $2;;
    spring-mvc) spring_mvc $2;;
    spring-webflux) spring_webflux $2;;
    thorntail) thorntail $2;;
    vertx) vertx $2;;
    -h | --help)
        echo "$MENSAGEM_USO"
        exit 0
        ;;
    *)
        echo "invalid option: $1"
        exit 1
        ;;
esac


